### ISSUE TITLE
rswarp.utilities.run_warp failing on jupyter server

### ISSUE THREAD

**Issue by cchall** [radiasoft/devops#71]
The run run_warp module in rswarp.utilities no longer seems to be working the Jupyter server recently.

run_warp.RunWarp is supposed to provide a wrapper that will take care of pathing for Warp output files and ensure that any output is not accidentally overwritten. It launches Warp using subprocess.Popen. 

It looks like it could be something with the virtual enviroment. Trying to execute a Warp script through run_warp.RunWarp gives errors for print statements that are not formatted for Python 3.
If the offending print statements are fixed then the run fails with a message that Warp is not installed.

**Comment by elventear** [comment]
Can you provide an example to reproduce the error?

**Comment by robnagler** [comment]
Here's what I get:

```
import warp
usage: __main__.py [-h] [-p DECOMP DECOMP DECOMP] [-l LOCALFLAGS]
                   [--pnumb PNUMB]
__main__.py: error: unrecognized arguments: -f /home/vagrant/.local/share/jupyter/runtime/kernel-8b61f588-abf0-4c0c-98dd-9232b9fe532f.json
```

**Comment by cchall** [comment]
This error occurs in the notebook:
heat_engine_sims/sow_01/task_1/notebooks/analysis_notebook.ipynb

**Comment by robnagler** [comment]
@cchall do you still need to clear sys.argv manually per radiasoft/containers#24?

**Comment by cchall** [comment]
Yes, that still needs to occur when calling 'from warp import *' from a
notebook.

**Comment by elventear** [comment]
@cchall could you try again?

**Comment by cchall** [comment]
@elventear I tried to restart my server but it is failing to start and just returns '500 Internal Server Error' after a minute.

**Comment by elventear** [comment]
@cchall I have fixed that issue. Please try again.

**Comment by cchall** [comment]
@elventear After restarting my server I am still unable to use run_warp.RunWarp.

**Comment by elventear** [comment]
@cchall last fix included auto-updates for `rsbeams` and `rssynergia`. I have added `rswarp`. Can you try again?

**Comment by cchall** [comment]
@elventear rswarp is now loading properly after restart. run_warp.RunWarp behavior has not changed.

**Comment by elventear** [comment]
I have a solution for the problem [here](https://github.com/radiasoft/rswarp/pull/2).

**Comment by robnagler** [comment]
I merged this change. @cchall please restart your container and again

**Comment by cchall** [comment]
run_warp.RunWarp now works for me in serial and parallel. (I added @elventear solution to the parallel run command)
